name: benchmarking
on:  [push, pull_request]

jobs:
  linux:
    name: benchmarking
    runs-on: ubuntu-latest
    env:
      HOST_WORKDIR:   /home/runner/work/benchmarking/benchmarking
      LICENSE_TAG:    BSD-3-Clause
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install packages
        run: sudo apt-get update && sudo apt-get install file -y

      - name: Run ansible linter
        uses: ansible/ansible-lint-action@master
        with:
          args: "-p"

      # execute test script in default location .github/run-tests.sh
      - name: Run tests - check license headers
        uses: skx/github-action-tester@master
